[package]
name = "discordnarok-timer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
serenity = "0.10"
serde = "1.0.130"
serde_json = "1.0"
